Workflow Demo

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,6 +31,39 @@ jobs:
             ./cycloneDX.json
             ./crypto_results.txt
 
+ name: SCANOSS WorkFlow Demo
+
+on:
+  push:
+    branches:
+      - '*'
+
+jobs:
+  scan-and-generate-sbom:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Log in to GitHub Docker Registry
+        if: env.DOCKER_AUTH_REQUIRED == 'true'
+        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+
+      - name: Run SCANOSS Analysis for License - Encryption - Vulnerabilities
+        run: |
+          docker pull ghcr.io/scanoss/scanoss-py:v1.19.0
+          docker run --rm -v $(pwd):/scanoss ghcr.io/scanoss/scanoss-py:v1.19.0 scan ./ --key ${{ secrets.SCANOSS_KEY }} --format cyclonedx -o cycloneDX.json
+          docker run --rm -v $(pwd):/scanoss ghcr.io/scanoss/scanoss-py:v1.19.0 comp crypto --key ${{ secrets.SCANOSS_KEY }} --purl pkg:github/heimdal/heimdal > crypto_results.txt
+
+      - name: Upload SBOM Results
+        uses: actions/upload-artifact@v4
+        with:
+          name: scanoss-results
+          path: |
+            ./cycloneDX.json
+            ./crypto_results.txt
+
   process-vulnerabilities:
     runs-on: ubuntu-latest
     needs: scan-and-generate-sbom
@@ -48,11 +81,18 @@ jobs:
       - name: Install Python Dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install pandas requests tabulate matplotlib kaleido
+          pip install pandas requests tabulate matplotlib kaleido numpy
 
       - name: Process EPSS, KEV, and NVD Data
         run: |
           python scripts/epss.py
+
+      - name: Check Generated Vulnerability Report
+        run: |
+          if [ ! -f vulnerability_report.json ]; then
+            echo "Error: vulnerability_report.json not found!"
+            exit 1
+          fi
 
       - name: Upload Enriched Vulnerability Data
         uses: actions/upload-artifact@v4
@@ -60,7 +100,7 @@ jobs:
           name: enriched-vulnerability-data
           path: vulnerability_report.json
 
-   generate-charts:
+  generate-charts:
     runs-on: ubuntu-latest
     needs: process-vulnerabilities
 
@@ -79,10 +119,19 @@ jobs:
           python -m pip install --upgrade pip
           pip install pandas requests tabulate matplotlib kaleido numpy
 
+      - name: Ensure Charts Directory Exists
+        run: mkdir -p charts
+
       - name: Generate Charts
         run: |
-          mkdir -p charts
           python scripts/generatecharts.py
+
+      - name: Check Generated Charts
+        run: |
+          if [ -z "$(ls -A charts)" ]; then
+            echo "Error: No charts were generated!"
+            exit 1
+          fi
 
       - name: Upload Charts
         uses: actions/upload-artifact@v4
